### ISSUE TITLE
Start a best-practices & performance page on docs.

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/docs.avohq.io#193]
Starting this from [this conversation](https://discord.com/channels/740892036978442260/1225792767754506240).

We need to highlight some of the things users should or shouldn't do to get more performance out of their apps.
We do that in certain sections, but an overview should be more useful.

Let's add it under the `configuration` section in the menu.

Some of the things we should talk about:

- avoiding n+1 using `include`
- avoiding `if/else` in fields
- about using blocks in `visible`, `disabled`, and more

**Open to more suggestions**

**Comment by jetienne** [comment]
@adrianthedev I would add: defaulting searchable: true on association, to avoid gigantic SELECT.

**Comment by MrJoy** [comment]
I'd suggest adding information about properly setting up STI.  In particular, the need to create resources for each STI sub-type, even if the presentation of entities won't vary.

**Comment by adrianthedev** [comment]
We have created [this page](https://docs.avohq.io/3.0/best-practices.html) to track best practices.

Will add [STI docs](https://github.com/avo-hq/docs.avohq.io/issues/204) soon.

We will have a better solution for `searchable` as a default [soon](https://github.com/avo-hq/avo/issues/2711).

Will close this for now, but let's keep the conversation open.
