### ISSUE TITLE
Add `default_sort_column`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/docs.avohq.io#251]
https://github.com/avo-hq/avo/pull/3018

**Comment by adrianthedev** [comment]
@icaroryan Could you please help with docs on this?

**Comment by icaroryan** [comment]
Hey guys, sorry for the delay. I’ve had some busy weeks. Just put up a PR for it <3

**Comment by Paul-Bob** [comment]
No problem @icaroryan, we appreciate it!
