### ISSUE TITLE
Typo: associtations -> associations

### ISSUE THREAD

**Issue by omarzina** [avo-hq/docs.avohq.io#285]
https://github.com/avo-hq/docs.avohq.io/blob/1019e3c9ac38dc65637737b1d6a30d40b564ab61/docs/3.0/resources.md?plain=1#L518

**Comment by Paul-Bob** [comment]
https://github.com/avo-hq/docs.avohq.io/commit/3a032c3a1e9474f08aed9e136e3b8e8fffeb36d4

Thank you @omarzina for reporting this.
